### PR TITLE
Instagram

### PR DESCRIPTION
**Pull request by mrjaques**

### CODE REVIEW

**Comment by Sheikhmohd** [comment]
#

**Comment by Sheikhmohd** [comment]
#1

**Comment by Sheikhmohd** [comment]
gh pr checkout 1

**Comment by Sheikhmohd** [comment]
package com.example.messagingstompwebsocket;

import org.springframework.context.annotation.Configuration;
import org.springframework.messaging.simp.config.MessageBrokerRegistry;
import org.springframework.web.socket.config.annotation.EnableWebSocketMessageBroker;
import org.springframework.web.socket.config.annotation.StompEndpointRegistry;
import org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer;

@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

  @Override
  public void configureMessageBroker(MessageBrokerRegistry config) {
    config.enableSimpleBroker("/topic");
    config.setApplicationDestinationPrefixes("/app");
  }

  @Override
  public void registerStompEndpoints(StompEndpointRegistry registry) {
    registry.addEndpoint("/gs-guide-websocket").withSockJS();
  }

}

**Review by Hybie009 — APPROVED** [review]

**Pull request closed without merging**
